- name: Create new project for quarkus-cafe
  command: "/usr/local/bin/oc new-project {{ project_namespace }}"
  register: create_project_result
  ignore_errors: yes
  when: not delete_deployment|bool

- name: Switch to project for quarkus-cafe
  command:  "/usr/local/bin/oc project {{ project_namespace }}"